LTKCPP-- LLRP Toolkit C Plus Plus Library: example1.cpp File Reference
example1.cpp File Reference
Simple example of LTKCPP that talks to an actual reader.
#include <stdio.h>
#include "ltkcpp.h"
Functions
int main (int ac, char *av[])
Command main routine.
void usage (char *pProgName)
Print usage message and exit.
Detailed Description
Simple example of LTKCPP that talks to an actual reader.
This is sometimes called the "LLRP Hello World" program
The steps:
Connect to the reader (TCP)
Make sure the connection status is good
Clear (scrub) the reader configuration
Add and enable a ROSpec that does a simple operation
Uses mostly default settings except for ROReportSpec
Uses all antennas
Starts on command
Runs for 5 seconds
Reports all accumulated tag observations
Run the ROSpec 5 times
Clear (scrub) the reader configuration
This program can be run with zero, one, or two verbose options (-v). no -v – Only prints the tag report and errors -v – Also prints one line progress messages -vv – Also prints all LLRP messages as XML text
This is sometimes called the "LLRP Hello World" program
The steps:
Initialize Library
Connect to Reader
Enable Impinj Extensions
Factory Default LLRP configuration to ensure that the reader is in a known state (since we are relying on the default reader configuration for this simple example)
ADD_ROSPEC to tell the reader to perform an inventory
ENABLE_ROSPEC
START_ROSPEC start the inventory operation
Process RFID Data (EPC, RSSI, Timestamp)
This program can be run with zero, one, or two verbose options (-v). no -v – Only prints the tag report and errors -v – Also prints one line progress messages -vv – Also prints all LLRP messages as XML text
Definition in file example1.cpp.
Function Documentation
int main (int ac, char * av[])
Command main routine.
Command synopsis:
example1 [-v[v]] READERHOSTNAME
0 Everything seemed to work. 1 Bad usage 2 Run failed
Command synopsis:
example1 [-v 0 -q 1 -p 23432] READERHOSTNAME
0 Everything seemed to work. 1 Bad usage 2 Run failed
Definition at line 165 of file example1.cpp.
References usage().
Referenced by convertFile().
void usage (char * pProgName)
Print usage message and exit.
Parameters
[in] nProgName Program name string
Returns
none, exits
Definition at line 247 of file example1.cpp.
Referenced by main().